//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string Iznos { get; set; }
        public System.DateTime Datum { get; set; }
    }
}
